/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post128, git sha1 b5170e139) */

(* top =  1  *)
(* src = "/tmp/ipykernel_4765/72881658.py:127" *)
(* generator = "Amaranth" *)
module top(cpu_out_1, cpu_out_2, cpu_out_3, cpu_out_4, cpu_out_5, cpu_out_6, cpu_out_7, cpu_out_8, cpu_out_9, cpu_out_10, cpu_out_11, gpu_out_0, gpu_out_1, gpu_out_2, gpu_out_3, npu_out_0, npu_out_1, npu_out_2, npu_out_3, npu_out_4, npu_out_5
, tpu_out_0, tpu_out_1, tpu_out_2, tpu_out_3, cpu_out_0);
  wire [32:0] \$1 ;
  wire [33:0] \$10 ;
  wire [33:0] \$11 ;
  wire [33:0] \$12 ;
  wire [32:0] \$2 ;
  wire [32:0] \$3 ;
  wire [32:0] \$4 ;
  wire [33:0] \$5 ;
  wire [33:0] \$6 ;
  wire [33:0] \$7 ;
  wire [33:0] \$8 ;
  wire [33:0] \$9 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  output [63:0] cpu_out_0;
  wire [63:0] cpu_out_0;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  output [63:0] cpu_out_1;
  wire [63:0] cpu_out_1;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  output [63:0] cpu_out_10;
  wire [63:0] cpu_out_10;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  output [63:0] cpu_out_11;
  wire [63:0] cpu_out_11;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  output [63:0] cpu_out_2;
  wire [63:0] cpu_out_2;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  output [63:0] cpu_out_3;
  wire [63:0] cpu_out_3;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  output [63:0] cpu_out_4;
  wire [63:0] cpu_out_4;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  output [63:0] cpu_out_5;
  wire [63:0] cpu_out_5;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  output [63:0] cpu_out_6;
  wire [63:0] cpu_out_6;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  output [63:0] cpu_out_7;
  wire [63:0] cpu_out_7;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  output [63:0] cpu_out_8;
  wire [63:0] cpu_out_8;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  output [63:0] cpu_out_9;
  wire [63:0] cpu_out_9;
  (* src = "/tmp/ipykernel_4765/72881658.py:81" *)
  output [31:0] gpu_out_0;
  wire [31:0] gpu_out_0;
  (* src = "/tmp/ipykernel_4765/72881658.py:81" *)
  output [31:0] gpu_out_1;
  wire [31:0] gpu_out_1;
  (* src = "/tmp/ipykernel_4765/72881658.py:81" *)
  output [31:0] gpu_out_2;
  wire [31:0] gpu_out_2;
  (* src = "/tmp/ipykernel_4765/72881658.py:81" *)
  output [31:0] gpu_out_3;
  wire [31:0] gpu_out_3;
  (* src = "/tmp/ipykernel_4765/72881658.py:22" *)
  output [63:0] npu_out_0;
  wire [63:0] npu_out_0;
  (* src = "/tmp/ipykernel_4765/72881658.py:22" *)
  output [63:0] npu_out_1;
  wire [63:0] npu_out_1;
  (* src = "/tmp/ipykernel_4765/72881658.py:22" *)
  output [63:0] npu_out_2;
  wire [63:0] npu_out_2;
  (* src = "/tmp/ipykernel_4765/72881658.py:22" *)
  output [63:0] npu_out_3;
  wire [63:0] npu_out_3;
  (* src = "/tmp/ipykernel_4765/72881658.py:22" *)
  output [63:0] npu_out_4;
  wire [63:0] npu_out_4;
  (* src = "/tmp/ipykernel_4765/72881658.py:22" *)
  output [63:0] npu_out_5;
  wire [63:0] npu_out_5;
  (* src = "/tmp/ipykernel_4765/72881658.py:107" *)
  output [31:0] tpu_out_0;
  wire [31:0] tpu_out_0;
  (* src = "/tmp/ipykernel_4765/72881658.py:107" *)
  output [31:0] tpu_out_1;
  wire [31:0] tpu_out_1;
  (* src = "/tmp/ipykernel_4765/72881658.py:107" *)
  output [31:0] tpu_out_2;
  wire [31:0] tpu_out_2;
  (* src = "/tmp/ipykernel_4765/72881658.py:107" *)
  output [31:0] tpu_out_3;
  wire [31:0] tpu_out_3;
  (* src = "/tmp/ipykernel_4765/72881658.py:128" *)
  \top.cpu  cpu (
    .\port$1$0 (\$1 ),
    .\port$10$0 (\$10 ),
    .\port$11$0 (\$11 ),
    .\port$12$0 (\$12 ),
    .\port$2$0 (\$2 ),
    .\port$3$0 (\$3 ),
    .\port$4$0 (\$4 ),
    .\port$5$0 (\$5 ),
    .\port$6$0 (\$6 ),
    .\port$7$0 (\$7 ),
    .\port$8$0 (\$8 ),
    .\port$9$0 (\$9 )
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:129" *)
  \top.gpu  gpu (
    .gpu_out_0(gpu_out_0),
    .gpu_out_1(gpu_out_1),
    .gpu_out_2(gpu_out_2),
    .gpu_out_3(gpu_out_3)
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:130" *)
  \top.npu  npu (
    .npu_out_0(npu_out_0),
    .npu_out_1(npu_out_1),
    .npu_out_2(npu_out_2),
    .npu_out_3(npu_out_3),
    .npu_out_4(npu_out_4),
    .npu_out_5(npu_out_5)
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:131" *)
  \top.tpu  tpu (
    .tpu_out_0(tpu_out_0),
    .tpu_out_1(tpu_out_1),
    .tpu_out_2(tpu_out_2),
    .tpu_out_3(tpu_out_3)
  );
  assign cpu_out_0 = { 31'h00000000, \$1  };
  assign cpu_out_1 = { 31'h00000000, \$2  };
  assign cpu_out_2 = { 31'h00000000, \$3  };
  assign cpu_out_3 = { 31'h00000000, \$4  };
  assign cpu_out_4 = { 30'h00000000, \$5  };
  assign cpu_out_5 = { 30'h00000000, \$6  };
  assign cpu_out_6 = { 30'h00000000, \$7  };
  assign cpu_out_7 = { 30'h00000000, \$8  };
  assign cpu_out_8 = { 30'h00000000, \$9  };
  assign cpu_out_9 = { 30'h00000000, \$10  };
  assign cpu_out_10 = { 30'h00000000, \$11  };
  assign cpu_out_11 = { 30'h00000000, \$12  };
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:58" *)
(* generator = "Amaranth" *)
module \top.cpu (\port$2$0 , \port$3$0 , \port$4$0 , \port$5$0 , \port$6$0 , \port$7$0 , \port$8$0 , \port$9$0 , \port$10$0 , \port$11$0 , \port$12$0 , \port$1$0 );
  wire [32:0] \$1 ;
  wire [33:0] \$10 ;
  wire [33:0] \$11 ;
  wire [33:0] \$12 ;
  wire [32:0] \$2 ;
  wire [32:0] \$3 ;
  wire [32:0] \$4 ;
  wire [33:0] \$5 ;
  wire [33:0] \$6 ;
  wire [33:0] \$7 ;
  wire [33:0] \$8 ;
  wire [33:0] \$9 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  wire [63:0] cpu_out_0;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  wire [63:0] cpu_out_1;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  wire [63:0] cpu_out_10;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  wire [63:0] cpu_out_11;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  wire [63:0] cpu_out_2;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  wire [63:0] cpu_out_3;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  wire [63:0] cpu_out_4;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  wire [63:0] cpu_out_5;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  wire [63:0] cpu_out_6;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  wire [63:0] cpu_out_7;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  wire [63:0] cpu_out_8;
  (* src = "/tmp/ipykernel_4765/72881658.py:55" *)
  wire [63:0] cpu_out_9;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] data_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] \data_out$11 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] \data_out$13 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] \data_out$15 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] \data_out$17 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] \data_out$19 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] \data_out$21 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] \data_out$23 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] \data_out$3 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] \data_out$5 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] \data_out$7 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] \data_out$9 ;
  output [32:0] \port$1$0 ;
  wire [32:0] \port$1$0 ;
  output [33:0] \port$10$0 ;
  wire [33:0] \port$10$0 ;
  output [33:0] \port$11$0 ;
  wire [33:0] \port$11$0 ;
  output [33:0] \port$12$0 ;
  wire [33:0] \port$12$0 ;
  output [32:0] \port$2$0 ;
  wire [32:0] \port$2$0 ;
  output [32:0] \port$3$0 ;
  wire [32:0] \port$3$0 ;
  output [32:0] \port$4$0 ;
  wire [32:0] \port$4$0 ;
  output [33:0] \port$5$0 ;
  wire [33:0] \port$5$0 ;
  output [33:0] \port$6$0 ;
  wire [33:0] \port$6$0 ;
  output [33:0] \port$7$0 ;
  wire [33:0] \port$7$0 ;
  output [33:0] \port$8$0 ;
  wire [33:0] \port$8$0 ;
  output [33:0] \port$9$0 ;
  wire [33:0] \port$9$0 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:61" *)
  \top.cpu.cpu_core_0  cpu_core_0 (
    .\port$1$0 (\$1 )
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:61" *)
  \top.cpu.cpu_core_1  cpu_core_1 (
    .\port$2$0 (\$2 )
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:61" *)
  \top.cpu.cpu_core_10  cpu_core_10 (
    .\port$11$0 (\$11 )
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:61" *)
  \top.cpu.cpu_core_11  cpu_core_11 (
    .\port$12$0 (\$12 )
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:61" *)
  \top.cpu.cpu_core_2  cpu_core_2 (
    .\port$3$0 (\$3 )
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:61" *)
  \top.cpu.cpu_core_3  cpu_core_3 (
    .\port$4$0 (\$4 )
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:61" *)
  \top.cpu.cpu_core_4  cpu_core_4 (
    .\port$5$0 (\$5 )
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:61" *)
  \top.cpu.cpu_core_5  cpu_core_5 (
    .\port$6$0 (\$6 )
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:61" *)
  \top.cpu.cpu_core_6  cpu_core_6 (
    .\port$7$0 (\$7 )
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:61" *)
  \top.cpu.cpu_core_7  cpu_core_7 (
    .\port$8$0 (\$8 )
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:61" *)
  \top.cpu.cpu_core_8  cpu_core_8 (
    .\port$9$0 (\$9 )
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:61" *)
  \top.cpu.cpu_core_9  cpu_core_9 (
    .\port$10$0 (\$10 )
  );
  assign cpu_out_0 = { 31'h00000000, \$1  };
  assign data_out = { 31'h00000000, \$1  };
  assign cpu_out_1 = { 31'h00000000, \$2  };
  assign \data_out$3  = { 31'h00000000, \$2  };
  assign cpu_out_2 = { 31'h00000000, \$3  };
  assign \data_out$5  = { 31'h00000000, \$3  };
  assign cpu_out_3 = { 31'h00000000, \$4  };
  assign \data_out$7  = { 31'h00000000, \$4  };
  assign cpu_out_4 = { 30'h00000000, \$5  };
  assign \data_out$9  = { 30'h00000000, \$5  };
  assign cpu_out_5 = { 30'h00000000, \$6  };
  assign \data_out$11  = { 30'h00000000, \$6  };
  assign cpu_out_6 = { 30'h00000000, \$7  };
  assign \data_out$13  = { 30'h00000000, \$7  };
  assign cpu_out_7 = { 30'h00000000, \$8  };
  assign \data_out$15  = { 30'h00000000, \$8  };
  assign cpu_out_8 = { 30'h00000000, \$9  };
  assign \data_out$17  = { 30'h00000000, \$9  };
  assign cpu_out_9 = { 30'h00000000, \$10  };
  assign \data_out$19  = { 30'h00000000, \$10  };
  assign cpu_out_10 = { 30'h00000000, \$11  };
  assign \data_out$21  = { 30'h00000000, \$11  };
  assign cpu_out_11 = { 30'h00000000, \$12  };
  assign \data_out$23  = { 30'h00000000, \$12  };
  assign \port$1$0  = \$1 ;
  assign \port$2$0  = \$2 ;
  assign \port$3$0  = \$3 ;
  assign \port$4$0  = \$4 ;
  assign \port$5$0  = \$5 ;
  assign \port$6$0  = \$6 ;
  assign \port$7$0  = \$7 ;
  assign \port$8$0  = \$8 ;
  assign \port$9$0  = \$9 ;
  assign \port$10$0  = \$10 ;
  assign \port$11$0  = \$11 ;
  assign \port$12$0  = \$12 ;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:46" *)
(* generator = "Amaranth" *)
module \top.cpu.cpu_core_0 (\port$1$0 );
  wire [32:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] data_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:42" *)
  wire [31:0] instruction;
  output [32:0] \port$1$0 ;
  wire [32:0] \port$1$0 ;
  assign data_out = { 31'h00000000, \$1  };
  assign instruction = 32'd0;
  assign \port$1$0  = \$1 ;
  assign \$1  = 33'h000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:46" *)
(* generator = "Amaranth" *)
module \top.cpu.cpu_core_1 (\port$2$0 );
  wire [32:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] data_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:42" *)
  wire [31:0] instruction;
  output [32:0] \port$2$0 ;
  wire [32:0] \port$2$0 ;
  assign data_out = { 31'h00000000, \$1  };
  assign instruction = 32'd0;
  assign \port$2$0  = \$1 ;
  assign \$1  = 33'h000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:46" *)
(* generator = "Amaranth" *)
module \top.cpu.cpu_core_10 (\port$11$0 );
  wire [33:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] data_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:42" *)
  wire [31:0] instruction;
  output [33:0] \port$11$0 ;
  wire [33:0] \port$11$0 ;
  assign data_out = { 30'h00000000, \$1  };
  assign instruction = 32'd0;
  assign \port$11$0  = \$1 ;
  assign \$1  = 34'h000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:46" *)
(* generator = "Amaranth" *)
module \top.cpu.cpu_core_11 (\port$12$0 );
  wire [33:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] data_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:42" *)
  wire [31:0] instruction;
  output [33:0] \port$12$0 ;
  wire [33:0] \port$12$0 ;
  assign data_out = { 30'h00000000, \$1  };
  assign instruction = 32'd0;
  assign \port$12$0  = \$1 ;
  assign \$1  = 34'h000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:46" *)
(* generator = "Amaranth" *)
module \top.cpu.cpu_core_2 (\port$3$0 );
  wire [32:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] data_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:42" *)
  wire [31:0] instruction;
  output [32:0] \port$3$0 ;
  wire [32:0] \port$3$0 ;
  assign data_out = { 31'h00000000, \$1  };
  assign instruction = 32'd0;
  assign \port$3$0  = \$1 ;
  assign \$1  = 33'h000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:46" *)
(* generator = "Amaranth" *)
module \top.cpu.cpu_core_3 (\port$4$0 );
  wire [32:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] data_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:42" *)
  wire [31:0] instruction;
  output [32:0] \port$4$0 ;
  wire [32:0] \port$4$0 ;
  assign data_out = { 31'h00000000, \$1  };
  assign instruction = 32'd0;
  assign \port$4$0  = \$1 ;
  assign \$1  = 33'h000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:46" *)
(* generator = "Amaranth" *)
module \top.cpu.cpu_core_4 (\port$5$0 );
  wire [33:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] data_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:42" *)
  wire [31:0] instruction;
  output [33:0] \port$5$0 ;
  wire [33:0] \port$5$0 ;
  assign data_out = { 30'h00000000, \$1  };
  assign instruction = 32'd0;
  assign \port$5$0  = \$1 ;
  assign \$1  = 34'h000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:46" *)
(* generator = "Amaranth" *)
module \top.cpu.cpu_core_5 (\port$6$0 );
  wire [33:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] data_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:42" *)
  wire [31:0] instruction;
  output [33:0] \port$6$0 ;
  wire [33:0] \port$6$0 ;
  assign data_out = { 30'h00000000, \$1  };
  assign instruction = 32'd0;
  assign \port$6$0  = \$1 ;
  assign \$1  = 34'h000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:46" *)
(* generator = "Amaranth" *)
module \top.cpu.cpu_core_6 (\port$7$0 );
  wire [33:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] data_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:42" *)
  wire [31:0] instruction;
  output [33:0] \port$7$0 ;
  wire [33:0] \port$7$0 ;
  assign data_out = { 30'h00000000, \$1  };
  assign instruction = 32'd0;
  assign \port$7$0  = \$1 ;
  assign \$1  = 34'h000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:46" *)
(* generator = "Amaranth" *)
module \top.cpu.cpu_core_7 (\port$8$0 );
  wire [33:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] data_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:42" *)
  wire [31:0] instruction;
  output [33:0] \port$8$0 ;
  wire [33:0] \port$8$0 ;
  assign data_out = { 30'h00000000, \$1  };
  assign instruction = 32'd0;
  assign \port$8$0  = \$1 ;
  assign \$1  = 34'h000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:46" *)
(* generator = "Amaranth" *)
module \top.cpu.cpu_core_8 (\port$9$0 );
  wire [33:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] data_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:42" *)
  wire [31:0] instruction;
  output [33:0] \port$9$0 ;
  wire [33:0] \port$9$0 ;
  assign data_out = { 30'h00000000, \$1  };
  assign instruction = 32'd0;
  assign \port$9$0  = \$1 ;
  assign \$1  = 34'h000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:46" *)
(* generator = "Amaranth" *)
module \top.cpu.cpu_core_9 (\port$10$0 );
  wire [33:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:43" *)
  wire [63:0] data_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:42" *)
  wire [31:0] instruction;
  output [33:0] \port$10$0 ;
  wire [33:0] \port$10$0 ;
  assign data_out = { 30'h00000000, \$1  };
  assign instruction = 32'd0;
  assign \port$10$0  = \$1 ;
  assign \$1  = 34'h000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:84" *)
(* generator = "Amaranth" *)
module \top.gpu (gpu_out_1, gpu_out_2, gpu_out_3, gpu_out_0);
  (* src = "/tmp/ipykernel_4765/72881658.py:71" *)
  output [31:0] gpu_out_0;
  wire [31:0] gpu_out_0;
  (* src = "/tmp/ipykernel_4765/72881658.py:71" *)
  output [31:0] gpu_out_1;
  wire [31:0] gpu_out_1;
  (* src = "/tmp/ipykernel_4765/72881658.py:71" *)
  output [31:0] gpu_out_2;
  wire [31:0] gpu_out_2;
  (* src = "/tmp/ipykernel_4765/72881658.py:71" *)
  output [31:0] gpu_out_3;
  wire [31:0] gpu_out_3;
  (* src = "/tmp/ipykernel_4765/72881658.py:71" *)
  wire [31:0] pixel_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:71" *)
  wire [31:0] \pixel_out$3 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:71" *)
  wire [31:0] \pixel_out$5 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:71" *)
  wire [31:0] \pixel_out$7 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:86" *)
  \top.gpu.shader_core_0  shader_core_0 (
    .pixel_out(gpu_out_0)
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:86" *)
  \top.gpu.shader_core_1  shader_core_1 (
    .pixel_out(gpu_out_1)
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:86" *)
  \top.gpu.shader_core_2  shader_core_2 (
    .pixel_out(gpu_out_2)
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:86" *)
  \top.gpu.shader_core_3  shader_core_3 (
    .pixel_out(gpu_out_3)
  );
  assign pixel_out = gpu_out_0;
  assign \pixel_out$3  = gpu_out_1;
  assign \pixel_out$5  = gpu_out_2;
  assign \pixel_out$7  = gpu_out_3;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:74" *)
(* generator = "Amaranth" *)
module \top.gpu.shader_core_0 (pixel_out);
  wire [32:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:70" *)
  wire [31:0] pixel_in;
  (* src = "/tmp/ipykernel_4765/72881658.py:71" *)
  output [31:0] pixel_out;
  wire [31:0] pixel_out;
  assign pixel_in = 32'd0;
  assign pixel_out = \$1 [31:0];
  assign \$1  = 33'h0000000ff;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:74" *)
(* generator = "Amaranth" *)
module \top.gpu.shader_core_1 (pixel_out);
  wire [32:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:70" *)
  wire [31:0] pixel_in;
  (* src = "/tmp/ipykernel_4765/72881658.py:71" *)
  output [31:0] pixel_out;
  wire [31:0] pixel_out;
  assign pixel_in = 32'd0;
  assign pixel_out = \$1 [31:0];
  assign \$1  = 33'h0000000ff;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:74" *)
(* generator = "Amaranth" *)
module \top.gpu.shader_core_2 (pixel_out);
  wire [32:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:70" *)
  wire [31:0] pixel_in;
  (* src = "/tmp/ipykernel_4765/72881658.py:71" *)
  output [31:0] pixel_out;
  wire [31:0] pixel_out;
  assign pixel_in = 32'd0;
  assign pixel_out = \$1 [31:0];
  assign \$1  = 33'h0000000ff;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:74" *)
(* generator = "Amaranth" *)
module \top.gpu.shader_core_3 (pixel_out);
  wire [32:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:70" *)
  wire [31:0] pixel_in;
  (* src = "/tmp/ipykernel_4765/72881658.py:71" *)
  output [31:0] pixel_out;
  wire [31:0] pixel_out;
  assign pixel_in = 32'd0;
  assign pixel_out = \$1 [31:0];
  assign \$1  = 33'h0000000ff;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:26" *)
(* generator = "Amaranth" *)
module \top.npu (npu_out_1, npu_out_2, npu_out_3, npu_out_4, npu_out_5, npu_out_0);
  (* src = "/tmp/ipykernel_4765/72881658.py:9" *)
  wire [63:0] data_in_a;
  (* src = "/tmp/ipykernel_4765/72881658.py:9" *)
  wire [63:0] \data_in_a$12 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:9" *)
  wire [63:0] \data_in_a$18 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:9" *)
  wire [63:0] \data_in_a$24 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:9" *)
  wire [63:0] \data_in_a$30 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:9" *)
  wire [63:0] \data_in_a$6 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:10" *)
  wire [63:0] data_in_b;
  (* src = "/tmp/ipykernel_4765/72881658.py:10" *)
  wire [63:0] \data_in_b$14 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:10" *)
  wire [63:0] \data_in_b$20 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:10" *)
  wire [63:0] \data_in_b$26 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:10" *)
  wire [63:0] \data_in_b$32 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:10" *)
  wire [63:0] \data_in_b$8 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:20" *)
  wire [63:0] npu_a_0;
  (* src = "/tmp/ipykernel_4765/72881658.py:20" *)
  wire [63:0] npu_a_1;
  (* src = "/tmp/ipykernel_4765/72881658.py:20" *)
  wire [63:0] npu_a_2;
  (* src = "/tmp/ipykernel_4765/72881658.py:20" *)
  wire [63:0] npu_a_3;
  (* src = "/tmp/ipykernel_4765/72881658.py:20" *)
  wire [63:0] npu_a_4;
  (* src = "/tmp/ipykernel_4765/72881658.py:20" *)
  wire [63:0] npu_a_5;
  (* src = "/tmp/ipykernel_4765/72881658.py:21" *)
  wire [63:0] npu_b_0;
  (* src = "/tmp/ipykernel_4765/72881658.py:21" *)
  wire [63:0] npu_b_1;
  (* src = "/tmp/ipykernel_4765/72881658.py:21" *)
  wire [63:0] npu_b_2;
  (* src = "/tmp/ipykernel_4765/72881658.py:21" *)
  wire [63:0] npu_b_3;
  (* src = "/tmp/ipykernel_4765/72881658.py:21" *)
  wire [63:0] npu_b_4;
  (* src = "/tmp/ipykernel_4765/72881658.py:21" *)
  wire [63:0] npu_b_5;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  output [63:0] npu_out_0;
  wire [63:0] npu_out_0;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  output [63:0] npu_out_1;
  wire [63:0] npu_out_1;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  output [63:0] npu_out_2;
  wire [63:0] npu_out_2;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  output [63:0] npu_out_3;
  wire [63:0] npu_out_3;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  output [63:0] npu_out_4;
  wire [63:0] npu_out_4;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  output [63:0] npu_out_5;
  wire [63:0] npu_out_5;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  wire [63:0] result;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  wire [63:0] \result$11 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  wire [63:0] \result$17 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  wire [63:0] \result$23 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  wire [63:0] \result$29 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  wire [63:0] \result$35 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:28" *)
  \top.npu.npu_core_0  npu_core_0 (
    .result(npu_out_0)
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:28" *)
  \top.npu.npu_core_1  npu_core_1 (
    .result(npu_out_1)
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:28" *)
  \top.npu.npu_core_2  npu_core_2 (
    .result(npu_out_2)
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:28" *)
  \top.npu.npu_core_3  npu_core_3 (
    .result(npu_out_3)
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:28" *)
  \top.npu.npu_core_4  npu_core_4 (
    .result(npu_out_4)
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:28" *)
  \top.npu.npu_core_5  npu_core_5 (
    .result(npu_out_5)
  );
  assign data_in_a = 64'h0000000000000000;
  assign npu_a_0 = 64'h0000000000000000;
  assign data_in_b = 64'h0000000000000000;
  assign npu_b_0 = 64'h0000000000000000;
  assign result = npu_out_0;
  assign \data_in_a$6  = 64'h0000000000000000;
  assign npu_a_1 = 64'h0000000000000000;
  assign \data_in_b$8  = 64'h0000000000000000;
  assign npu_b_1 = 64'h0000000000000000;
  assign \result$11  = npu_out_1;
  assign \data_in_a$12  = 64'h0000000000000000;
  assign npu_a_2 = 64'h0000000000000000;
  assign \data_in_b$14  = 64'h0000000000000000;
  assign npu_b_2 = 64'h0000000000000000;
  assign \result$17  = npu_out_2;
  assign \data_in_a$18  = 64'h0000000000000000;
  assign npu_a_3 = 64'h0000000000000000;
  assign \data_in_b$20  = 64'h0000000000000000;
  assign npu_b_3 = 64'h0000000000000000;
  assign \result$23  = npu_out_3;
  assign \data_in_a$24  = 64'h0000000000000000;
  assign npu_a_4 = 64'h0000000000000000;
  assign \data_in_b$26  = 64'h0000000000000000;
  assign npu_b_4 = 64'h0000000000000000;
  assign \result$29  = npu_out_4;
  assign \data_in_a$30  = 64'h0000000000000000;
  assign npu_a_5 = 64'h0000000000000000;
  assign \data_in_b$32  = 64'h0000000000000000;
  assign npu_b_5 = 64'h0000000000000000;
  assign \result$35  = npu_out_5;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:14" *)
(* generator = "Amaranth" *)
module \top.npu.npu_core_0 (result);
  wire [127:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:9" *)
  wire [63:0] data_in_a;
  (* src = "/tmp/ipykernel_4765/72881658.py:10" *)
  wire [63:0] data_in_b;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  output [63:0] result;
  wire [63:0] result;
  assign data_in_a = 64'h0000000000000000;
  assign data_in_b = 64'h0000000000000000;
  assign result = \$1 [63:0];
  assign \$1  = 128'h00000000000000000000000000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:14" *)
(* generator = "Amaranth" *)
module \top.npu.npu_core_1 (result);
  wire [127:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:9" *)
  wire [63:0] data_in_a;
  (* src = "/tmp/ipykernel_4765/72881658.py:10" *)
  wire [63:0] data_in_b;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  output [63:0] result;
  wire [63:0] result;
  assign data_in_a = 64'h0000000000000000;
  assign data_in_b = 64'h0000000000000000;
  assign result = \$1 [63:0];
  assign \$1  = 128'h00000000000000000000000000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:14" *)
(* generator = "Amaranth" *)
module \top.npu.npu_core_2 (result);
  wire [127:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:9" *)
  wire [63:0] data_in_a;
  (* src = "/tmp/ipykernel_4765/72881658.py:10" *)
  wire [63:0] data_in_b;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  output [63:0] result;
  wire [63:0] result;
  assign data_in_a = 64'h0000000000000000;
  assign data_in_b = 64'h0000000000000000;
  assign result = \$1 [63:0];
  assign \$1  = 128'h00000000000000000000000000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:14" *)
(* generator = "Amaranth" *)
module \top.npu.npu_core_3 (result);
  wire [127:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:9" *)
  wire [63:0] data_in_a;
  (* src = "/tmp/ipykernel_4765/72881658.py:10" *)
  wire [63:0] data_in_b;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  output [63:0] result;
  wire [63:0] result;
  assign data_in_a = 64'h0000000000000000;
  assign data_in_b = 64'h0000000000000000;
  assign result = \$1 [63:0];
  assign \$1  = 128'h00000000000000000000000000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:14" *)
(* generator = "Amaranth" *)
module \top.npu.npu_core_4 (result);
  wire [127:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:9" *)
  wire [63:0] data_in_a;
  (* src = "/tmp/ipykernel_4765/72881658.py:10" *)
  wire [63:0] data_in_b;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  output [63:0] result;
  wire [63:0] result;
  assign data_in_a = 64'h0000000000000000;
  assign data_in_b = 64'h0000000000000000;
  assign result = \$1 [63:0];
  assign \$1  = 128'h00000000000000000000000000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:14" *)
(* generator = "Amaranth" *)
module \top.npu.npu_core_5 (result);
  wire [127:0] \$1 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:9" *)
  wire [63:0] data_in_a;
  (* src = "/tmp/ipykernel_4765/72881658.py:10" *)
  wire [63:0] data_in_b;
  (* src = "/tmp/ipykernel_4765/72881658.py:11" *)
  output [63:0] result;
  wire [63:0] result;
  assign data_in_a = 64'h0000000000000000;
  assign data_in_b = 64'h0000000000000000;
  assign result = \$1 [63:0];
  assign \$1  = 128'h00000000000000000000000000000000;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:110" *)
(* generator = "Amaranth" *)
module \top.tpu (tpu_out_1, tpu_out_2, tpu_out_3, tpu_out_0);
  (* src = "/tmp/ipykernel_4765/72881658.py:97" *)
  wire [31:0] acc_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:97" *)
  wire [31:0] \acc_out$3 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:97" *)
  wire [31:0] \acc_out$5 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:97" *)
  wire [31:0] \acc_out$7 ;
  (* src = "/tmp/ipykernel_4765/72881658.py:97" *)
  output [31:0] tpu_out_0;
  wire [31:0] tpu_out_0;
  (* src = "/tmp/ipykernel_4765/72881658.py:97" *)
  output [31:0] tpu_out_1;
  wire [31:0] tpu_out_1;
  (* src = "/tmp/ipykernel_4765/72881658.py:97" *)
  output [31:0] tpu_out_2;
  wire [31:0] tpu_out_2;
  (* src = "/tmp/ipykernel_4765/72881658.py:97" *)
  output [31:0] tpu_out_3;
  wire [31:0] tpu_out_3;
  (* src = "/tmp/ipykernel_4765/72881658.py:112" *)
  \top.tpu.tpu_cell_0  tpu_cell_0 (
    .acc_out(tpu_out_0)
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:112" *)
  \top.tpu.tpu_cell_1  tpu_cell_1 (
    .acc_out(tpu_out_1)
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:112" *)
  \top.tpu.tpu_cell_2  tpu_cell_2 (
    .acc_out(tpu_out_2)
  );
  (* src = "/tmp/ipykernel_4765/72881658.py:112" *)
  \top.tpu.tpu_cell_3  tpu_cell_3 (
    .acc_out(tpu_out_3)
  );
  assign acc_out = tpu_out_0;
  assign \acc_out$3  = tpu_out_1;
  assign \acc_out$5  = tpu_out_2;
  assign \acc_out$7  = tpu_out_3;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:100" *)
(* generator = "Amaranth" *)
module \top.tpu.tpu_cell_0 (acc_out);
  (* src = "/tmp/ipykernel_4765/72881658.py:97" *)
  output [31:0] acc_out;
  wire [31:0] acc_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:96" *)
  wire [15:0] activation;
  (* src = "/tmp/ipykernel_4765/72881658.py:95" *)
  wire [15:0] weight;
  assign weight = 16'h0000;
  assign activation = 16'h0000;
  assign acc_out = 32'd0;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:100" *)
(* generator = "Amaranth" *)
module \top.tpu.tpu_cell_1 (acc_out);
  (* src = "/tmp/ipykernel_4765/72881658.py:97" *)
  output [31:0] acc_out;
  wire [31:0] acc_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:96" *)
  wire [15:0] activation;
  (* src = "/tmp/ipykernel_4765/72881658.py:95" *)
  wire [15:0] weight;
  assign weight = 16'h0000;
  assign activation = 16'h0000;
  assign acc_out = 32'd0;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:100" *)
(* generator = "Amaranth" *)
module \top.tpu.tpu_cell_2 (acc_out);
  (* src = "/tmp/ipykernel_4765/72881658.py:97" *)
  output [31:0] acc_out;
  wire [31:0] acc_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:96" *)
  wire [15:0] activation;
  (* src = "/tmp/ipykernel_4765/72881658.py:95" *)
  wire [15:0] weight;
  assign weight = 16'h0000;
  assign activation = 16'h0000;
  assign acc_out = 32'd0;
endmodule

(* src = "/tmp/ipykernel_4765/72881658.py:100" *)
(* generator = "Amaranth" *)
module \top.tpu.tpu_cell_3 (acc_out);
  (* src = "/tmp/ipykernel_4765/72881658.py:97" *)
  output [31:0] acc_out;
  wire [31:0] acc_out;
  (* src = "/tmp/ipykernel_4765/72881658.py:96" *)
  wire [15:0] activation;
  (* src = "/tmp/ipykernel_4765/72881658.py:95" *)
  wire [15:0] weight;
  assign weight = 16'h0000;
  assign activation = 16'h0000;
  assign acc_out = 32'd0;
endmodule
