name: Auto Trigger Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v4

      - name: Checkout Private Chip IP
        uses: actions/checkout@v4
        with:
          repository: 'FQ-studio/FQ-Store-Private-'
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: 'private_chip'

      - name: Verify Secure IP Access
        run: |
          echo "Memeriksa capaian fail peribadi..."
          ls -la private_chip/
          echo "Fail IP peribadi berjaya dicapai secara selamat!"
