name: FQ Technology Shop CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Build Test
        run: echo "FQ Technology Shop Workflow Executed Successfully!"
